###
# Cluster API
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: application
    component: app-cluster-api
  name: app-cluster-api
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: application
      component: app-cluster-api
  template:
    metadata:
      labels:
        cluster: application
        component: app-cluster-api
    spec:
      containers:
      - name: app-cluster-api
        image: nalejregistry.azurecr.io/nalej/app-cluster-api:VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
