kind: Service
apiVersion: v1
metadata:
  name: app-cluster-api
  labels:
    cluster: application
    component: app-cluster-api
  namespace: __NPH_NAMESPACE
spec:
  selector:
    cluster: application
    component: app-cluster-api
  type: ClusterIP
  ports:
  - protocol: TCP
    name: grpc
    port: 8281
    targetPort: 8281
